### ISSUE TITLE
Create Shopping Cart Product component

### ISSUE THREAD

**Issue by mrpeterhanley** [chingu-voyages/v26-geckos-team-04#11]

**Comment by yumip** [comment]
![image](https://user-images.githubusercontent.com/71173724/104453140-15261600-55f8-11eb-82ab-bcbbd5e9e2e3.png)

**Comment by yumip** [comment]
![image](https://user-images.githubusercontent.com/71173724/104453433-82d24200-55f8-11eb-83ae-b04d1c9376d4.png)
So this is a component for each product in the shopping cart?
